"""Check the final plot files, including composited supplementary figures.

This validator confirms that the figures keep the same plotted data and remain
interpretable both in color and after grayscale conversion.
"""
from pathlib import Path
import json
import ast
import numpy as np
from PIL import Image
ROOT=Path(__file__).resolve().parent
F=ROOT/'figures'
# Confirm the actual sampling expression, not a separate display-only constant.
sampling=[]
for node in ast.walk(ast.parse((ROOT/'analyze_r3.py').read_text())):
    if (isinstance(node,ast.Call) and isinstance(node.func,ast.Attribute)
            and node.func.attr=='clip' and len(node.args)==3):
        z=node.args[0]
        if isinstance(z,ast.Call) and isinstance(z.func,ast.Attribute) and z.func.attr=='normal':
            sampling.append([ast.literal_eval(v) for v in z.args+node.args[1:]])
assert sampling==[[12000,4000,2000,25000]],sampling
checks=json.loads((F/'figure_style_checks.json').read_text())
rows=[]
for p in sorted(F.glob('*.png')):
    a=np.asarray(Image.open(p).convert('RGB'))
    gray=np.asarray(Image.open(p).convert('L'))
    # File should contain some intentional color, but remain non-blank after grayscale conversion.
    colored=int(((a[:,:,0]!=a[:,:,1])|(a[:,:,1]!=a[:,:,2])).sum())
    contrast=int(gray.max())-int(gray.min())
    if contrast < 25:
        raise ValueError(f'Insufficient grayscale contrast in {p.name}: {contrast}')
    rows.append({'file':p.name,'width_px':a.shape[1],'height_px':a.shape[0],'colored_pixels':colored,'grayscale_contrast':contrast})
# Key figures must remain distinguishable without relying on color.
for stem in ['fig2_shock_sweep','fig6_added_seasons']:
    assert stem in checks,stem
    enc=[(x['linestyle'],x['marker']) for x in checks[stem]['series']]
    assert len(enc)==len(set(enc)),f'Ambiguous dash-marker pairs: {stem}'
for key in ['january_2025','elliott_2022','uri_2021']:
    for pre in ['fig4_','figS7_']:
        enc=[(x['linestyle'],x['marker']) for x in checks[pre+key]['series']]
        assert len(enc)==len(set(enc)),(pre,key,enc)
for v in checks.values():
    assert v['plotted_arrays_unchanged'] and v['axis_limits_unchanged'] and v['area_geometry_unchanged']
assert len(rows)>=28
out={'status':'PASS','png_files':len(rows),'individually_styled_figures':len(checks),
     'all_png_have_grayscale_contrast':True,'selected_series_distinguishable_without_color':True,
     'sampling_normal_mean_sd_clip_bounds_mw':sampling[0],
     'scope':'Checks the figure sources generated by this computational package.',
     'files':rows}
(ROOT/'results'/'figure_style_verification.json').write_text(json.dumps(out,indent=2)+'\n')
print(json.dumps({k:v for k,v in out.items() if k!='files'},indent=2))
